name: Django Application

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: testdb
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres_user

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code 
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
      
      - name: Install dependencies 
        run: |
          pip install -r requirements_dev.txt
          cat contrib/env-sample >> .env

#      - name: Install postgreSQL client
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y postgresql-client


      - name: Test With Flake8
        run: flake8

#      - name: Test With Pytest
#        run: pytest --cov=pypro

#      - name: codecov
#        run: codecov
