name: Django Application

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: testdb
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres_user

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code 
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
      
      - name: Install dependencies 
        run: |
          pip install -r requirements_dev.txt
          cat contrib/env-sample >> .env

#     - name: Install postgreSQL client
#       run: |
#         apt-get update
#         apt-get install --yes postgresql-client

#     - name: Query database
#       run: psql -h postgres -d postgres_db -U postgres_user -c 'SELECT 1'
#       env:
#         PGPASSWORD: postgres_password

      - name: Test With Flake8
        uses: py-actions/flake8@v1
        with:
          checkName: 'flake8_py3' 

      - name: Test With Pytest
        run: pytest --cov=pypro

      - name: codecov
        run: codecov
