name: Django Application

on:
  pull_request:
  push:
    branchs:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code 
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
        env:
          - PIPENV_VENV_IN_PROJECT=1
          - PIPENV_IGNORE_VIRTUALENVS=1

      - name: Install dependencies 
        run: pip install -q pipenv
        run: pipenv sync --dev
      
      - name: Test With Flake8
        run: flake8 .